Repository svg-sprite/svg-sprite, pull requests merged in 2022-05, with the labels that each got.

#606 Update @resvg/resvg-js to v2.0.0
  lib/svg-sprite/utils/calculate-svg-dimensions.js
  package-lock.json
  package.json
Labels: dependencies, no-squash

#677 Update devDependencies and regenerate package-lock.json
  package-lock.json
  package.json
Labels: dependencies

#682 Substitute ID references in href attributes
  lib/svg-sprite/shape.js
  test/svg-sprite/shape/shape.svg.namespace.test.js
  test/svg-sprite/shape/shape.svg.test.js
Labels: enhancement

#688 Downgrade playwright due to different screenshot quality with & without plugged power source
  package-lock.json
  package.json
Labels: dependencies
