Repository svg-sprite/svg-sprite, pull requests merged in 2022-04, with the labels that each got.

#654 add tests for `SVGShape`
  lib/svg-sprite/shape.js
  lib/svg-sprite/utils/index.js
  test/svg-sprite/shape/shape.svg.test.js
Labels: tests

#656 add more tests for `SVGShape`
  test/svg-sprite/shape/shape.svg.test.js
Labels: tests

#661 add more tests for `SVGShape`
  lib/svg-sprite/shape.js
  test/svg-sprite/shape/shape.complement.test.js
  test/svg-sprite/shape/shape.svg.test.js
Labels: tests

#663 adding tests for `SVGSprite`
  lib/svg-sprite/sprite.js
  test/svg-sprite/sprite.test.js
Labels: tests

#660 Update dependencies
  package-lock.json
  package.json
Labels: dependencies

#664 change SVGSprite to an ES6 class
  lib/svg-sprite/sprite.js
Labels: enhancement

#666 Add support for disabling root viewBox attribute in stack mode
  bin/config.yaml
  docs/configuration.md
  lib/svg-sprite/mode/stack.js
  test/expected/png/stack-without-viewbox.html.png
  test/svg-sprite/minimal-configuration/modes/stack.test.js
Labels: enhancement

#668 Update devDependencies
  package-lock.json
  package.json
Labels: dependencies

#508 config: Abstract config code to smaller functions
  lib/svg-sprite/config.js
Labels: refactor

#665 add tests for `SVGSpriteBase`
  lib/svg-sprite/mode/base.js
  test/svg-sprite/mode/base.test.js
Labels: tests
