Repository svg-sprite/svg-sprite, pull requests merged in 2022-10, with the labels that each got.

#746 Update dependencies and regenerate package-lock.json
  package-lock.json
  package.json
Labels: dependencies

#747 remove-temp-path: drop pre Node.js 14 fallback
  test/helpers/remove-temp-path.js
Labels: tests

#745 Fix `shape.id.separator` regression
  lib/svg-sprite/shape.js
  test/svg-sprite/shape/shape.constructor.test.js
Labels: bug
