Repository svg-sprite/svg-sprite, pull requests merged in 2022-06, with the labels that each got.

#620 Replace `_.escape` with native JS
  lib/svg-sprite/sprite.js
  lib/svg-sprite/utils/index.js
  test/utils.test.js
Labels: refactor

#619 Switch to the `lodash.merge` package
  bin/svg-sprite.js
  lib/svg-sprite.js
  lib/svg-sprite/layouter.js
  lib/svg-sprite/mode/base.js
  lib/svg-sprite/shape.js
  lib/svg-sprite/transform/svgo.js
  package-lock.json
  package.json
Labels: dependencies

#461 Replace `_.invoke` with vanilla JS
  lib/svg-sprite.js
Labels: refactor

#700 Replace `_.trim` and `_.trimStart` with `lodash.trim` and `lodash.trimstart`
  lib/svg-sprite.js
  package-lock.json
  package.json
Labels: dependencies, refactor

#701 Update dependencies
  package-lock.json
  package.json
Labels: dependencies
