Repository svg-sprite/svg-sprite, pull requests merged in 2022-11, with the labels that each got.

#751 Update dependencies
  package-lock.json
  package.json
Labels: dependencies

#752 CI: switch to Node.js 18
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: github_actions

#749 refactor: drop `lodash.trim` dependency
  lib/svg-sprite.js
  package-lock.json
  package.json
Labels: dependencies, squash

#757 CI: remove git credentials after checkout
  .github/workflows/codeql.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: ci

#756 Update devDependencies
  package-lock.json
  package.json
Labels: dependencies

#759 Update codeql.yml
  .github/workflows/codeql.yml
Labels: ci

#591 Use for...of loops when possible
  README.md
  bin/svg-sprite.js
  docs/api.md
  example.js
  lib/svg-sprite.js
  lib/svg-sprite/config.js
  lib/svg-sprite/layouter.js
  lib/svg-sprite/mode/base.js
  lib/svg-sprite/mode/css.js
  lib/svg-sprite/mode/css/packer.js
  lib/svg-sprite/mode/stack.js
  lib/svg-sprite/mode/standalone.js
  lib/svg-sprite/mode/symbol.js
  lib/svg-sprite/mode/view.js
  lib/svg-sprite/shape.js
  lib/svg-sprite/sprite.js
  package.json
  test/helpers/add-files.js
  test/helpers/write-files.js
  test/svg-shape.test.js
  test/svg-sprite/shape/shape.svg.namespace.test.js
Labels: refactor, squash

#764 chore: upgrade resvg-js to 2.2.0
  package-lock.json
  package.json
Labels: dependencies

#602 shape.js: use a Set for classnames
  lib/svg-sprite/shape.js
Labels: refactor
