Repository svg-sprite/svg-sprite, pull requests merged in 2022-09, with the labels that each got.

#725 Updated svgo.test.js
  test/svg-sprite/transform/svgo.test.js
Labels: tests

#705 Fixed #288: Preserving `@font-face` in style defs
  lib/svg-sprite/shape.js
  test/svg-sprite/special/font-face.test.js
Labels: bug

#704 Added snapshots testing for regression tests
  test/svg-sprite/alignment/__snapshots__/center.test.js.snap
  test/svg-sprite/alignment/__snapshots__/mixed.test.js.snap
  test/svg-sprite/alignment/center.test.js
  test/svg-sprite/alignment/mixed.test.js
  test/svg-sprite/minimal-configuration/modes/__snapshots__/css.test.js.snap
  test/svg-sprite/minimal-configuration/modes/__snapshots__/defs.test.js.snap
  test/svg-sprite/minimal-configuration/modes/__snapshots__/stack.test.js.snap
  test/svg-sprite/minimal-configuration/modes/__snapshots__/symbol.test.js.snap
  test/svg-sprite/minimal-configuration/modes/__snapshots__/view.mixed.test.js.snap
  test/svg-sprite/minimal-configuration/modes/__snapshots__/view.packed.test.js.snap
  test/svg-sprite/minimal-configuration/modes/css.test.js
  test/svg-sprite/minimal-configuration/modes/defs.test.js
  test/svg-sprite/minimal-configuration/modes/stack.test.js
  test/svg-sprite/minimal-configuration/modes/symbol.test.js
  test/svg-sprite/minimal-configuration/modes/view.mixed.test.js
  test/svg-sprite/minimal-configuration/modes/view.packed.test.js
Labels: tests

#726 Replaced `Error.errno` with Error classes
  lib/svg-sprite.js
  lib/svg-sprite/errors/argument-error.js
  lib/svg-sprite/errors/dimensions-calculation-error.js
  lib/svg-sprite/errors/not-permitted-error.js
  lib/svg-sprite/errors/xml-fixing-error.js
  lib/svg-sprite/shape.js
  lib/svg-sprite/utils/calculate-svg-dimensions.js
  lib/svg-sprite/utils/fix-xml-string.js
  test/calculate-svg-dimensions.test.js
  test/fix-xml-string.test.js
  test/svg-shape.test.js
  test/svg-sprite/shape/shape.complement.test.js
  test/svg-sprite/shape/shape.svg.namespace.test.js
Labels: refactor

#733 Update minor dependencies
  package-lock.json
  package.json
Labels: dependencies
