Repository svg-sprite/svg-sprite, pull requests merged in 2022-03, with the labels that each got.

#596 Downgrade csso to v4.
  package-lock.json
  package.json
Labels: dependencies

#590 feat: decrease Lodash usage
  bin/svg-sprite.js
  lib/svg-sprite.js
  lib/svg-sprite/config.js
  lib/svg-sprite/mode/base.js
  lib/svg-sprite/mode/css.js
  lib/svg-sprite/mode/standalone.js
  lib/svg-sprite/shape.js
  lib/svg-sprite/sprite.js
  lib/svg-sprite/utils/index.js
  test/helpers/write-files.js
  test/shape.test.js
  test/utils.test.js
Labels: refactor

#607 feat: adding async compile method (returns Promise)
  README.md
  docs/api.md
  lib/svg-sprite.js
  test/svg-sprite/minimal-configuration/error.test.js
  test/svg-sprite/minimal-configuration/no-arguments.test.js
Labels: enhancement

#572 feat: moving from mocha to jest
  .c8rc.json
  .mocharc.json
  jest.config.js
  lib/svg-sprite/shape.js
  package-lock.json
  package.json
  test/calculate-svg-dimensions.test.js
  test/fix-xml-string.test.js
  test/helpers/async-renderers.js
  test/helpers/capture-puppeteer.js
  test/helpers/compare-svg-2-png-helper.js
  test/helpers/compare-svg-2-png.js
  test/helpers/convert-svg-2-png.js
  test/helpers/remove-temp-path.js
  test/helpers/write-file.js
  test/jest/setup.global.js
  test/jest/setup.js
  test/shape.test.js
  test/spriter.test.js
  test/svg-shape.test.js
  test/svg-sprite/alignment/center.test.js
  test/svg-sprite/alignment/mixed.test.js
  test/svg-sprite/minimal-configuration/error.test.js
  test/svg-sprite/minimal-configuration/modes/css.test.js
  test/svg-sprite/minimal-configuration/modes/symbol.test.js
  test/svg-sprite/minimal-configuration/modes/view.mixed.test.js
  test/svg-sprite/minimal-configuration/modes/view.packed.test.js
  test/svg-sprite/minimal-configuration/no-arguments.test.js
  test/svg-sprite/minimal-configuration/rerun.test.js
  test/utils.test.js
Labels: dependencies, refactor, tests

#609 Update devDependencies and regenerate package-lock.json
  package-lock.json
  package.json
Labels: dependencies

#612 feat: split `css.packed.aligned.png` into two files for more clear tests
  test/expected/png/css.packed.centered.png
  test/expected/png/css.packed.mixed.png
  test/svg-sprite/alignment/center.test.js
  test/svg-sprite/minimal-configuration/modes/view.mixed.test.js
Labels: tests

#610 Move from puppeteer & looks-same to playwright & pixelmatch for more stable tests
  package-lock.json
  package.json
  test/helpers/capture-browser.js
  test/helpers/capture-puppeteer.js
  test/helpers/compare-html-2-png.js
  test/helpers/compare-png-2-png.js
  test/helpers/compare-svg-2-png-helper.js
  test/helpers/compare-svg-2-png.js
  test/helpers/constants.js
  test/helpers/convert-svg-2-png.js
  test/jest/setup.js
Labels: dependencies, tests

#463 Replace `_.pick` with native JS
  lib/svg-sprite/config.js
  lib/svg-sprite/mode/css.js
Labels: refactor

#625 fixing saving diff and docs in tests
  test/helpers/compare-png-2-png.js
Labels: bug, tests

#622 Replace `_.cloneDeep` with `_.merge`
  lib/svg-sprite.js
  lib/svg-sprite/layouter.js
  lib/svg-sprite/shape.js
  lib/svg-sprite/transform/svgo.js
Labels: refactor

#621 add test for stack mode
  test/expected/png/stack-without-dims.html.png
  test/expected/png/stack.html.png
  test/svg-sprite/minimal-configuration/modes/stack.test.js
  test/tmpl/stack.html
Labels: enhancement, tests

#628 add test for `layouter.layout`
  test/svg-sprite/layouter.test.js
Labels: tests

#627 fix: checking passed config.log to be instance of winston.Logger
  lib/svg-sprite/config.js
  test/svg-sprite/config.test.js
Labels: bug, tests

#629 Update dependencies
  package-lock.json
  package.json
Labels: dependencies

#630 Bring back lodash backport compatibility for `utils.isObject`
  lib/svg-sprite/utils/index.js
  test/utils.test.js
Labels: tests

#631 add more layouter tests
  test/svg-sprite/layouter.test.js
Labels: tests

#634 add tests for `SVGSpriterConfig.filter`
  test/svg-sprite/config.test.js
Labels: tests

#632 Convert SVGSpriteLayouter to ES6 class
  lib/svg-sprite/layouter.js
Labels: refactor

#636 config tests refactoring
  test/svg-sprite/config.test.js
  test/svg-sprite/config/config.constructor.attributes.test.js
  test/svg-sprite/config/config.constructor.log.test.js
  test/svg-sprite/config/config.filter.test.js
Labels: refactor, tests

#637 add test for `shape.meta` creation in SVGSpriterConfig
  test/svg-sprite/config/config.constructor.attributes.test.js
  test/svg-sprite/config/config.constructor.shape.test.js
Labels: tests

#638 add tests for `shape.align` creation in SVGSpriterConfig
  test/svg-sprite/config/config.constructor.attributes.test.js
  test/svg-sprite/config/config.constructor.shape.align.test.js
  test/svg-sprite/config/config.constructor.shape.meta.test.js
Labels: tests

#551 Replace deprecated getter/setter methods with `Object.defineProperty`
  lib/svg-sprite/mode/css.js
  lib/svg-sprite/mode/defs.js
  lib/svg-sprite/mode/stack.js
  lib/svg-sprite/mode/standalone.js
  lib/svg-sprite/mode/symbol.js
Labels: refactor

#640 Convert Queue to an ES6 class
  lib/svg-sprite/queue.js
Labels: refactor

#642 Convert packer to an ES6 class
  lib/svg-sprite/mode/css/packer.js
Labels: refactor

#643 add tests for `shape.transform` & `shape.spacing` in SVGSpriterConfig
  test/svg-sprite/config/config.constructor.shape.spacing.test.js
  test/svg-sprite/config/config.constructor.shape.transforms.test.js
Labels: tests

#646 add tests for `shape.svg` in SVGSpriterConfig.constructor
  test/svg-sprite/config/config.constructor.svg.test.js
Labels: tests

#648 add test for `calculate-svg-dimensions`
  test/calculate-svg-dimensions.test.js
Labels: tests

#644 Convert Config to an ES6 class
  lib/svg-sprite/config.js
Labels: refactor

#647 add tests for `transform/svgo`
  test/svg-sprite/transform/svgo.test.js
Labels: tests

#649 add test for packer.js
  lib/svg-sprite/mode/css/packer.js
  test/svg-sprite/mode/css.packer.test.js
Labels: tests

#552 packer: deduplicate code
  lib/svg-sprite/mode/css/packer.js
Labels: refactor

#650 add tests for `Queue`
  test/svg-sprite/queue.test.js
Labels: tests
